//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zilon.TextClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zilon.TextClient.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not do this.
        /// </summary>
        internal static string CommandCantExecuteMessage {
            get {
                return ResourceManager.GetString("CommandCantExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot;dead&quot; to dead :).
        /// </summary>
        internal static string DeadCommandDescription {
            get {
                return ResourceManager.GetString("DeadCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        internal static string EffectsLabel {
            get {
                return ResourceManager.GetString("EffectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot;exit&quot; to quit the game..
        /// </summary>
        internal static string ExitCommandDescription {
            get {
                return ResourceManager.GetString("ExitCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globe created.
        /// </summary>
        internal static string GlobeGenerationCompleteMessage {
            get {
                return ResourceManager.GetString("GlobeGenerationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot;idle&quot; to wait some time..
        /// </summary>
        internal static string IdleCommandDescription {
            get {
                return ResourceManager.GetString("IdleCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your command.
        /// </summary>
        internal static string InputPrompt {
            get {
                return ResourceManager.GetString("InputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot;look&quot; to get detailet info around..
        /// </summary>
        internal static string LookCommandDescription {
            get {
                return ResourceManager.GetString("LookCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monster.
        /// </summary>
        internal static string MonsterNodeMarker {
            get {
                return ResourceManager.GetString("MonsterNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - &quot;move [x] [y]&quot; to move person..
        /// </summary>
        internal static string MoveCommandDescription {
            get {
                return ResourceManager.GetString("MoveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NextNodeMarker {
            get {
                return ResourceManager.GetString("NextNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        internal static string NodesLabel {
            get {
                return ResourceManager.GetString("NodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string PersonsLabel {
            get {
                return ResourceManager.GetString("PersonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to continue....
        /// </summary>
        internal static string PressEnterToContinuePropmpt {
            get {
                return ResourceManager.GetString("PressEnterToContinuePropmpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        internal static string StaticObjectNodeMarker {
            get {
                return ResourceManager.GetString("StaticObjectNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string TransitionNodeMarker {
            get {
                return ResourceManager.GetString("TransitionNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string UndiscaveredNodeMarker {
            get {
                return ResourceManager.GetString("UndiscaveredNodeMarker", resourceCulture);
            }
        }
    }
}
