//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zilon.TextClient {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zilon.TextClient.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;attack [id] a&quot; to attack enemy (or &quot;s&quot;to attack object).
        /// </summary>
        internal static string AttackCommandDescription {
            get {
                return ResourceManager.GetString("AttackCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can not do this.
        /// </summary>
        internal static string CommandCantExecuteMessage {
            get {
                return ResourceManager.GetString("CommandCantExecuteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;dead&quot; to get dead :).
        /// </summary>
        internal static string DeadCommandDescription {
            get {
                return ResourceManager.GetString("DeadCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effects.
        /// </summary>
        internal static string EffectsLabel {
            get {
                return ResourceManager.GetString("EffectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;exit&quot; to quit the game..
        /// </summary>
        internal static string ExitCommandDescription {
            get {
                return ResourceManager.GetString("ExitCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Globe created.
        /// </summary>
        internal static string GlobeGenerationCompleteMessage {
            get {
                return ResourceManager.GetString("GlobeGenerationCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;idle&quot; to wait some time..
        /// </summary>
        internal static string IdleCommandDescription {
            get {
                return ResourceManager.GetString("IdleCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input your command.
        /// </summary>
        internal static string InputPrompt {
            get {
                return ResourceManager.GetString("InputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;look&quot; to get detailed info around..
        /// </summary>
        internal static string LookCommandDescription {
            get {
                return ResourceManager.GetString("LookCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на monster.
        /// </summary>
        internal static string MonsterNodeMarker {
            get {
                return ResourceManager.GetString("MonsterNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;move [x] [y]&quot; to move person..
        /// </summary>
        internal static string MoveCommandDescription {
            get {
                return ResourceManager.GetString("MoveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string NextNodeMarker {
            get {
                return ResourceManager.GetString("NextNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A cell closest to the player person..
        /// </summary>
        internal static string NextNodeMarkerDescription {
            get {
                return ResourceManager.GetString("NextNodeMarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nodes.
        /// </summary>
        internal static string NodesLabel {
            get {
                return ResourceManager.GetString("NodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Persons.
        /// </summary>
        internal static string PersonsLabel {
            get {
                return ResourceManager.GetString("PersonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press [Enter] to continue....
        /// </summary>
        internal static string PressEnterToContinuePropmpt {
            get {
                return ResourceManager.GetString("PressEnterToContinuePropmpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на object.
        /// </summary>
        internal static string StaticObjectNodeMarker {
            get {
                return ResourceManager.GetString("StaticObjectNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - &quot;transit&quot; to go to next level.
        /// </summary>
        internal static string TransitionCommandDescription {
            get {
                return ResourceManager.GetString("TransitionCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на t.
        /// </summary>
        internal static string TransitionNodeMarker {
            get {
                return ResourceManager.GetString("TransitionNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A cell with transition to other level..
        /// </summary>
        internal static string TransitionNodeMarkerDescription {
            get {
                return ResourceManager.GetString("TransitionNodeMarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на u.
        /// </summary>
        internal static string UndiscoveredNextNodeMarker {
            get {
                return ResourceManager.GetString("UndiscoveredNextNodeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A cell which have unknown cells near..
        /// </summary>
        internal static string UndiscoveredNextNodeMarkerDescription {
            get {
                return ResourceManager.GetString("UndiscoveredNextNodeMarkerDescription", resourceCulture);
            }
        }
    }
}
