name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Codebase improvements'
    labels:
      - 'code improvement'
      - 'continuous integration'
      - 'documentarium'
change-template: |
  ### $TITLE (#$NUMBER)
  
  $BODY
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
include-labels:
  - 'release-significant'
prerelease: true
sort-direction: ascending
template: |
  ## What's news

  $CHANGES
