coverage:
  status:
    project:
      default:
        target: 40%
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%