// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Zilon.Core.Spec.TestCases
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Fight_ToHit_Failure", Description="\tЧтобы было противостояние наступление и обороны\r\n\tКак разработчику\r\n\tМне нужно, " +
        "чтобы персонаж не мог попадать по противнику, если тот умеет оборонятся против т" +
        "ипа нападения действия.", SourceFile="TestCases\\Fight_ToHit_Failure.feature", SourceLine=0)]
    public partial class Fight_ToHit_FailureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Fight_ToHit_Failure.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Fight_ToHit_Failure", "\tЧтобы было противостояние наступление и обороны\r\n\tКак разработчику\r\n\tМне нужно, " +
                    "чтобы персонаж не мог попадать по противнику, если тот умеет оборонятся против т" +
                    "ипа нападения действия.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_(string personSid, string equipmentSid, string monsterSid, string monsterId, string monsterNodeX, string monsterNodeY, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "fight",
                    "dev0"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
                    "ь обороны проив этого действия.", null, @__tags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("Есть карта размером 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("Есть актёр игрока класса {0} в ячейке (0, 0)", personSid), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("Есть монстр класса {0} Id:{1} в ячейке ({2}, {3})", monsterSid, monsterId, monsterNodeX, monsterNodeY), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("Актёр игрока экипирован предметом {0} в слот Index: 2", equipmentSid), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When(string.Format("Актёр игрока атакует монстра Id:{0}", monsterId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then(string.Format("Монстр Id:{0} успешно обороняется", monsterId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 0", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant0()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "short-sword", "pretorian", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 1", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant1()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "battle-axe", "pretorian", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 2", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant2()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "shadow-staff", "hound", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 3", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant3()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "stilleto", "hound", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 4", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant4()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "sniper-rifle", "jocker", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Промахи действий с определённым типом нападения, если у противника высокий уровен" +
            "ь обороны проив этого действия., Variant 5", new string[] {
                "fight",
                "dev0"}, SourceLine=16)]
        public virtual void ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия__Variant5()
        {
#line 7
this.ПромахиДействийСОпределённымТипомНападенияЕслиУПротивникаВысокийУровеньОбороныПроивЭтогоДействия_("captain", "minigun", "jocker", "1000", "0", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
