// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Zilon.Core.Spec.TestCases
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Survival_ConsumeProviantToDropSurvivalEffect", Description="\tЧтобы ввести микроменеджмент ресурсов и состояния персонажей\r\n\tКак игроку\r\n\tМне " +
        "нужно, чтобы каждый ход значение сытости персонажа падало", SourceFile="TestCases\\Survival_ConsumeProviantToDropSurvivalEffect.feature", SourceLine=0)]
    public partial class Survival_ConsumeProviantToDropSurvivalEffectFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Survival_ConsumeProviantToDropSurvivalEffect.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Survival_ConsumeProviantToDropSurvivalEffect", "\tЧтобы ввести микроменеджмент ресурсов и состояния персонажей\r\n\tКак игроку\r\n\tМне " +
                    "нужно, чтобы каждый ход значение сытости персонажа падало", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_(string stat, string statValue, string startEffect, string propSid, string propCount, string expectedValue, string effect, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "survival",
                    "dev0"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод).", null, @__tags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("Есть произвольная карта", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("Есть актёр игрока", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("Актёр значение {0} равное {1}", stat, statValue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("Актёр имеет эффект {0}", startEffect), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("В инвентаре у актёра есть еда: {0} количество: {1}", propSid, propCount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When(string.Format("Актёр использует предмет {0} на себя", propSid), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then(string.Format("Значение {0} стало {1}", stat, expectedValue), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.And(string.Format("Актёр под эффектом {0}", effect), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 0", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant0()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("сытость", "0", "Слабый голод", "cheese", "1", "9", "нет", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 1", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant1()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("сытость", "-25", "Голод", "cheese", "1", "-16", "Слабый голод", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 2", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant2()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("сытость", "-50", "Голодание", "cheese", "1", "-41", "Голод", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 3", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant3()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("вода", "0", "Слабая жажда", "water", "1", "9", "нет", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 4", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant4()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("вода", "-25", "Жажда", "water", "1", "-16", "Слабая жажда", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Поглощение провианта, чтобы снимать выживальные состояния (жажда/голод)., Variant" +
            " 5", new string[] {
                "survival",
                "dev0"}, SourceLine=18)]
        public virtual void ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод__Variant5()
        {
#line 7
this.ПоглощениеПровиантаЧтобыСниматьВыживальныеСостоянияЖаждаГолод_("вода", "-50", "Обезвоживание", "water", "1", "-41", "Жажда", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
