//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.LAST.MonoGameClient.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CDT.LAST.MonoGameClient.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DiseaseSymptomConditionTitle {
            get {
                return ResourceManager.GetString("DiseaseSymptomConditionTitle", resourceCulture);
            }
        }
        
        internal static string HungerCriticalConditionTitle {
            get {
                return ResourceManager.GetString("HungerCriticalConditionTitle", resourceCulture);
            }
        }
        
        internal static string HungerLesserConditionTitle {
            get {
                return ResourceManager.GetString("HungerLesserConditionTitle", resourceCulture);
            }
        }
        
        internal static string HungerStrongConditionTitle {
            get {
                return ResourceManager.GetString("HungerStrongConditionTitle", resourceCulture);
            }
        }
        
        internal static string IntoxicationCriticalConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationCriticalConditionTitle", resourceCulture);
            }
        }
        
        internal static string IntoxicationLesserConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationLesserConditionTitle", resourceCulture);
            }
        }
        
        internal static string IntoxicationStrongConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationStrongConditionTitle", resourceCulture);
            }
        }
        
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        internal static string ThristCriticalConditionTitle {
            get {
                return ResourceManager.GetString("ThristCriticalConditionTitle", resourceCulture);
            }
        }
        
        internal static string ThristLesserConditionTitle {
            get {
                return ResourceManager.GetString("ThristLesserConditionTitle", resourceCulture);
            }
        }
        
        internal static string ThristStrongConditionTitle {
            get {
                return ResourceManager.GetString("ThristStrongConditionTitle", resourceCulture);
            }
        }
        
        internal static string WoundCriticalConditionTitle {
            get {
                return ResourceManager.GetString("WoundCriticalConditionTitle", resourceCulture);
            }
        }
        
        internal static string WoundLesserConditionTitle {
            get {
                return ResourceManager.GetString("WoundLesserConditionTitle", resourceCulture);
            }
        }
        
        internal static string WoundStrongConditionTitle {
            get {
                return ResourceManager.GetString("WoundStrongConditionTitle", resourceCulture);
            }
        }
        
        internal static string GenerateGlobeButtonTitle {
            get {
                return ResourceManager.GetString("GenerateGlobeButtonTitle", resourceCulture);
            }
        }
        
        internal static string SwitchAutomodeButtonOffTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOffTitle", resourceCulture);
            }
        }
        
        internal static string SwitchAutomodeButtonOnTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOnTitle", resourceCulture);
            }
        }
        
        internal static string SwitchAutomodeButtonTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonTitle", resourceCulture);
            }
        }
        
        internal static string PhysicalStrengthAttributeTitle {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeTitle", resourceCulture);
            }
        }
        
        internal static string DexterityAttributeTitle {
            get {
                return ResourceManager.GetString("DexterityAttributeTitle", resourceCulture);
            }
        }
        
        internal static string PerceptionAttributeTitle {
            get {
                return ResourceManager.GetString("PerceptionAttributeTitle", resourceCulture);
            }
        }
        
        internal static string ConstitutionAttributeTitle {
            get {
                return ResourceManager.GetString("ConstitutionAttributeTitle", resourceCulture);
            }
        }
        
        internal static string PhysicalStrengthAttributeDescription {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeDescription", resourceCulture);
            }
        }
        
        internal static string DexterityAttributeDescription {
            get {
                return ResourceManager.GetString("DexterityAttributeDescription", resourceCulture);
            }
        }
        
        internal static string PerceptionAttributeDescription {
            get {
                return ResourceManager.GetString("PerceptionAttributeDescription", resourceCulture);
            }
        }
        
        internal static string ConstitutionAttributeDescription {
            get {
                return ResourceManager.GetString("ConstitutionAttributeDescription", resourceCulture);
            }
        }
        
        internal static string UbnormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("UbnormalAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string DefectiveAttributeValueTitle {
            get {
                return ResourceManager.GetString("DefectiveAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string LowAttributeValueTitle {
            get {
                return ResourceManager.GetString("LowAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string NormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("NormalAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string BelowNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("BelowNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string AboveNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("AboveNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string SuperAttributeValueTitle {
            get {
                return ResourceManager.GetString("SuperAttributeValueTitle", resourceCulture);
            }
        }
        
        internal static string HealCommandButtonTitle {
            get {
                return ResourceManager.GetString("HealCommandButtonTitle", resourceCulture);
            }
        }
        
        internal static string EatCommandButtonTitle {
            get {
                return ResourceManager.GetString("EatCommandButtonTitle", resourceCulture);
            }
        }
        
        internal static string DrinkCommandButtonTitle {
            get {
                return ResourceManager.GetString("DrinkCommandButtonTitle", resourceCulture);
            }
        }
        
        internal static string UseCommandButtonTitle {
            get {
                return ResourceManager.GetString("UseCommandButtonTitle", resourceCulture);
            }
        }
        
        internal static string EquipInSlotTemplateCommandButton {
            get {
                return ResourceManager.GetString("EquipInSlotTemplateCommandButton", resourceCulture);
            }
        }
        
        internal static string SlotHand {
            get {
                return ResourceManager.GetString("SlotHand", resourceCulture);
            }
        }
        
        internal static string SlotHead {
            get {
                return ResourceManager.GetString("SlotHead", resourceCulture);
            }
        }
        
        internal static string SlotBody {
            get {
                return ResourceManager.GetString("SlotBody", resourceCulture);
            }
        }
        
        internal static string SlotAux {
            get {
                return ResourceManager.GetString("SlotAux", resourceCulture);
            }
        }
        
        internal static string TakePropInInventoryButtonTitle {
            get {
                return ResourceManager.GetString("TakePropInInventoryButtonTitle", resourceCulture);
            }
        }
        
        internal static string PutPropInContainerButtonTitleTemplate {
            get {
                return ResourceManager.GetString("PutPropInContainerButtonTitleTemplate", resourceCulture);
            }
        }
        
        internal static string FakeContainerName {
            get {
                return ResourceManager.GetString("FakeContainerName", resourceCulture);
            }
        }
        
        internal static string MainMenuButtonTitle {
            get {
                return ResourceManager.GetString("MainMenuButtonTitle", resourceCulture);
            }
        }
        
        internal static string NextScreenButtonTitle {
            get {
                return ResourceManager.GetString("NextScreenButtonTitle", resourceCulture);
            }
        }
        
        internal static string ScoreMenuTitle {
            get {
                return ResourceManager.GetString("ScoreMenuTitle", resourceCulture);
            }
        }
        
        internal static string LeaderboardMenuTitle {
            get {
                return ResourceManager.GetString("LeaderboardMenuTitle", resourceCulture);
            }
        }
    }
}
