//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.LAST.MonoGameClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDT.LAST.MonoGameClient.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string AboveNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("AboveNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add nickname.
        /// </summary>
        internal static string AddPlayerNicknameButton {
            get {
                return ResourceManager.GetString("AddPlayerNicknameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string BelowNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("BelowNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearPlayerNicknameButton {
            get {
                return ResourceManager.GetString("ClearPlayerNicknameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affects how many wounds can
        ///take out the character before he dies..
        /// </summary>
        internal static string ConstitutionAttributeDescription {
            get {
                return ResourceManager.GetString("ConstitutionAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string ConstitutionAttributeTitle {
            get {
                return ResourceManager.GetString("ConstitutionAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LMB] to move and attack.
        ///[T] to transit to other stage.
        ///[O] to give loot up.
        ///[I] to open inventory.
        ///[C] to open character stats.
        ///[SPACE] to wait a little..
        /// </summary>
        internal static string ControlsTutorialText {
            get {
                return ResourceManager.GetString("ControlsTutorialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defective.
        /// </summary>
        internal static string DefectiveAttributeValueTitle {
            get {
                return ResourceManager.GetString("DefectiveAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility, physical flexibility of the character, stretching.
        ///Acts as a restriction on equipment, such as daggers, staves..
        /// </summary>
        internal static string DexterityAttributeDescription {
            get {
                return ResourceManager.GetString("DexterityAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string DexterityAttributeTitle {
            get {
                return ResourceManager.GetString("DexterityAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        internal static string DiseaseSymptomConditionTitle {
            get {
                return ResourceManager.GetString("DiseaseSymptomConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        internal static string DrinkCommandButtonTitle {
            get {
                return ResourceManager.GetString("DrinkCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eat.
        /// </summary>
        internal static string EatCommandButtonTitle {
            get {
                return ResourceManager.GetString("EatCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy is needed to deliver powerful blows.
        ///When the energy ends, the character gets tired.
        ///A tired character is less effective in combat.
        ///And the exhausted character begins to lose vitality
        ///and may die of overwork..
        /// </summary>
        internal static string EnergyConditionDescription {
            get {
                return ResourceManager.GetString("EnergyConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXHAUSTED!.
        /// </summary>
        internal static string EnergyCriticalConditionTitle {
            get {
                return ResourceManager.GetString("EnergyCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy tired.
        /// </summary>
        internal static string EnergyLesserConditionTitle {
            get {
                return ResourceManager.GetString("EnergyLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tired.
        /// </summary>
        internal static string EnergyStrongConditionTitle {
            get {
                return ResourceManager.GetString("EnergyStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip in slot: {0}.
        /// </summary>
        internal static string EquipInSlotTemplateCommandButton {
            get {
                return ResourceManager.GetString("EquipInSlotTemplateCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the loot bag.
        /// </summary>
        internal static string FakeContainerName {
            get {
                return ResourceManager.GetString("FakeContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateGlobeButtonTitle {
            get {
                return ResourceManager.GetString("GenerateGlobeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string HealCommandButtonTitle {
            get {
                return ResourceManager.GetString("HealCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any character needs to eat.
        ///A hungry character is less efficient.
        ///Ultimately, starvation kills the character..
        /// </summary>
        internal static string HungerConditionDescription {
            get {
                return ResourceManager.GetString("HungerConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starvation!.
        /// </summary>
        internal static string HungerCriticalConditionTitle {
            get {
                return ResourceManager.GetString("HungerCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy hunger.
        /// </summary>
        internal static string HungerLesserConditionTitle {
            get {
                return ResourceManager.GetString("HungerLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunger.
        /// </summary>
        internal static string HungerStrongConditionTitle {
            get {
                return ResourceManager.GetString("HungerStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of medicines increases the level of intoxication of the character.
        ///Toxins slightly reduce the effectiveness of the character,
        ///but erode over time.
        ///If the intoxication grows too much, an overdose will occur.
        ///and the character will die..
        /// </summary>
        internal static string IntoxicationConditionDescription {
            get {
                return ResourceManager.GetString("IntoxicationConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERDOSE!.
        /// </summary>
        internal static string IntoxicationCriticalConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy intoxication.
        /// </summary>
        internal static string IntoxicationLesserConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intoxication.
        /// </summary>
        internal static string IntoxicationStrongConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard menu.
        /// </summary>
        internal static string LeaderboardMenuTitle {
            get {
                return ResourceManager.GetString("LeaderboardMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LowAttributeValueTitle {
            get {
                return ResourceManager.GetString("LowAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenuButtonTitle {
            get {
                return ResourceManager.GetString("MainMenuButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextScreenButtonTitle {
            get {
                return ResourceManager.GetString("NextScreenButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneEquipmentTitle {
            get {
                return ResourceManager.GetString("NoneEquipmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string NormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("NormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception, sight. Ability to see, notice.
        ///Acts as a restriction on the use of ranged weapons.
        ///Or weapons based on precise strikes rather than strength (daggers, spears)..
        /// </summary>
        internal static string PerceptionAttributeDescription {
            get {
                return ResourceManager.GetString("PerceptionAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        internal static string PerceptionAttributeTitle {
            get {
                return ResourceManager.GetString("PerceptionAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical, brute strength of the character.
        ///Affects melee weapon damage.
        ///Acts as a restriction on the wearing of heavy equipment..
        /// </summary>
        internal static string PhysicalStrengthAttributeDescription {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Strength.
        /// </summary>
        internal static string PhysicalStrengthAttributeTitle {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your nickname.
        /// </summary>
        internal static string PlayerInputNicknamePrompt {
            get {
                return ResourceManager.GetString("PlayerInputNicknamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your leader board rating: {0}.
        /// </summary>
        internal static string PlayerRatingLabel {
            get {
                return ResourceManager.GetString("PlayerRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put into {0}.
        /// </summary>
        internal static string PutPropInContainerButtonTitleTemplate {
            get {
                return ResourceManager.GetString("PutPropInContainerButtonTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score menu.
        /// </summary>
        internal static string ScoreMenuTitle {
            get {
                return ResourceManager.GetString("ScoreMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string ScoreTableNickColumnTitle {
            get {
                return ResourceManager.GetString("ScoreTableNickColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ScoreTableNumberColumnTitle {
            get {
                return ResourceManager.GetString("ScoreTableNumberColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string ScoreTableScoreColumnTitle {
            get {
                return ResourceManager.GetString("ScoreTableScoreColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux.
        /// </summary>
        internal static string SlotAux {
            get {
                return ResourceManager.GetString("SlotAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string SlotBody {
            get {
                return ResourceManager.GetString("SlotBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        internal static string SlotHand {
            get {
                return ResourceManager.GetString("SlotHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string SlotHead {
            get {
                return ResourceManager.GetString("SlotHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super.
        /// </summary>
        internal static string SuperAttributeValueTitle {
            get {
                return ResourceManager.GetString("SuperAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SwitchAutomodeButtonOffTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string SwitchAutomodeButtonOnTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay: {0}.
        /// </summary>
        internal static string SwitchAutomodeButtonTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lang.
        /// </summary>
        internal static string SwitchLanguagebuttonTitle {
            get {
                return ResourceManager.GetString("SwitchLanguagebuttonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch res.
        /// </summary>
        internal static string SwitchResolutionButtonTitle {
            get {
                return ResourceManager.GetString("SwitchResolutionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take in inventory.
        /// </summary>
        internal static string TakePropInInventoryButtonTitle {
            get {
                return ResourceManager.GetString("TakePropInInventoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All characters need to drink.\n
        ///Thirst reduces the effectiveness of characters\n
        ///and can lead to dehydration.\n
        ///Dehydration is death!.
        /// </summary>
        internal static string ThristConditionDescription {
            get {
                return ResourceManager.GetString("ThristConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dehydration!.
        /// </summary>
        internal static string ThristCriticalConditionTitle {
            get {
                return ResourceManager.GetString("ThristCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy thrist.
        /// </summary>
        internal static string ThristLesserConditionTitle {
            get {
                return ResourceManager.GetString("ThristLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrist.
        /// </summary>
        internal static string ThristStrongConditionTitle {
            get {
                return ResourceManager.GetString("ThristStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubnormal.
        /// </summary>
        internal static string UbnormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("UbnormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string UseCommandButtonTitle {
            get {
                return ResourceManager.GetString("UseCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is alive as long as he has vitality.
        ///Damage, external or internal, takes away vitality.
        ///Gradually, any wounds heal. Ultimately, the game
        ///continues as long as there is at least some life in the character..
        /// </summary>
        internal static string WoundConditionDescription {
            get {
                return ResourceManager.GetString("WoundConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortal wound!.
        /// </summary>
        internal static string WoundCriticalConditionTitle {
            get {
                return ResourceManager.GetString("WoundCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesser wound.
        /// </summary>
        internal static string WoundLesserConditionTitle {
            get {
                return ResourceManager.GetString("WoundLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong wound.
        /// </summary>
        internal static string WoundStrongConditionTitle {
            get {
                return ResourceManager.GetString("WoundStrongConditionTitle", resourceCulture);
            }
        }
    }
}
