//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.LAST.MonoGameClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDT.LAST.MonoGameClient.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        internal static string DiseaseSymptomConditionTitle {
            get {
                return ResourceManager.GetString("DiseaseSymptomConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateGlobeButtonTitle {
            get {
                return ResourceManager.GetString("GenerateGlobeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starvation!.
        /// </summary>
        internal static string HungerCriticalConditionTitle {
            get {
                return ResourceManager.GetString("HungerCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy hunger.
        /// </summary>
        internal static string HungerLesserConditionTitle {
            get {
                return ResourceManager.GetString("HungerLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunger.
        /// </summary>
        internal static string HungerStrongConditionTitle {
            get {
                return ResourceManager.GetString("HungerStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTOXICATION!.
        /// </summary>
        internal static string IntoxicationCriticalConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy intoxication.
        /// </summary>
        internal static string IntoxicationLesserConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intoxication.
        /// </summary>
        internal static string IntoxicationStrongConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dehydration!.
        /// </summary>
        internal static string ThristCriticalConditionTitle {
            get {
                return ResourceManager.GetString("ThristCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy thrist.
        /// </summary>
        internal static string ThristLesserConditionTitle {
            get {
                return ResourceManager.GetString("ThristLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrist.
        /// </summary>
        internal static string ThristStrongConditionTitle {
            get {
                return ResourceManager.GetString("ThristStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortal wound!.
        /// </summary>
        internal static string WoundCriticalConditionTitle {
            get {
                return ResourceManager.GetString("WoundCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesser wound.
        /// </summary>
        internal static string WoundLesserConditionTitle {
            get {
                return ResourceManager.GetString("WoundLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong wound.
        /// </summary>
        internal static string WoundStrongConditionTitle {
            get {
                return ResourceManager.GetString("WoundStrongConditionTitle", resourceCulture);
            }
        }
    }
}
