#!/bin/bash

# Полный путь к проекту. Последний слеш не нужен.
PathToProject='[project-path]'
# Полный путь к ReSharperCLT https://www.jetbrains.com/resharper/features/command-line.html
# Без слеша в конце.
PathToReSharperClt="$PathToProject\Tools\working-directory\resharper-clt"

PathToSolutionFile="$PathToProject\Zilon.Core\Zilon.Core.sln"

RED="\033[0;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
NC="\033[0m" # No Color

# Запускаем чистку кода.

echo -e "${YELLOW}Запускаем чистку кода на солюшне $PathToSolutionFile${NC}"
"$PathToReSharperClt\CleanupCode.exe" "$PathToSolutionFile" --exclude="**/Migrations/*"

exit 0
