//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDT.LAST.MonoGameClient.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDT.LAST.MonoGameClient.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Above normal.
        /// </summary>
        internal static string AboveNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("AboveNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Below normal.
        /// </summary>
        internal static string BelowNormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("BelowNormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Affects how many wounds can
        ///take out the character before he dies..
        /// </summary>
        internal static string ConstitutionAttributeDescription {
            get {
                return ResourceManager.GetString("ConstitutionAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constitution.
        /// </summary>
        internal static string ConstitutionAttributeTitle {
            get {
                return ResourceManager.GetString("ConstitutionAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Defective.
        /// </summary>
        internal static string DefectiveAttributeValueTitle {
            get {
                return ResourceManager.GetString("DefectiveAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agility, physical flexibility of the character, stretching.
        ///Acts as a restriction on equipment, such as daggers, staves..
        /// </summary>
        internal static string DexterityAttributeDescription {
            get {
                return ResourceManager.GetString("DexterityAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dexterity.
        /// </summary>
        internal static string DexterityAttributeTitle {
            get {
                return ResourceManager.GetString("DexterityAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disease.
        /// </summary>
        internal static string DiseaseSymptomConditionTitle {
            get {
                return ResourceManager.GetString("DiseaseSymptomConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drink.
        /// </summary>
        internal static string DrinkCommandButtonTitle {
            get {
                return ResourceManager.GetString("DrinkCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eat.
        /// </summary>
        internal static string EatCommandButtonTitle {
            get {
                return ResourceManager.GetString("EatCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equip in slot: {0}.
        /// </summary>
        internal static string EquipInSlotTemplateCommandButton {
            get {
                return ResourceManager.GetString("EquipInSlotTemplateCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the loot bag.
        /// </summary>
        internal static string FakeContainerName {
            get {
                return ResourceManager.GetString("FakeContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate.
        /// </summary>
        internal static string GenerateGlobeButtonTitle {
            get {
                return ResourceManager.GetString("GenerateGlobeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heal.
        /// </summary>
        internal static string HealCommandButtonTitle {
            get {
                return ResourceManager.GetString("HealCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starvation!.
        /// </summary>
        internal static string HungerCriticalConditionTitle {
            get {
                return ResourceManager.GetString("HungerCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy hunger.
        /// </summary>
        internal static string HungerLesserConditionTitle {
            get {
                return ResourceManager.GetString("HungerLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hunger.
        /// </summary>
        internal static string HungerStrongConditionTitle {
            get {
                return ResourceManager.GetString("HungerStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INTOXICATION!.
        /// </summary>
        internal static string IntoxicationCriticalConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy intoxication.
        /// </summary>
        internal static string IntoxicationLesserConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intoxication.
        /// </summary>
        internal static string IntoxicationStrongConditionTitle {
            get {
                return ResourceManager.GetString("IntoxicationStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low.
        /// </summary>
        internal static string LowAttributeValueTitle {
            get {
                return ResourceManager.GetString("LowAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Normal.
        /// </summary>
        internal static string NormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("NormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perception, sight. Ability to see, notice.
        ///Acts as a restriction on the use of ranged weapons.
        ///Or weapons based on precise strikes rather than strength (daggers, spears)..
        /// </summary>
        internal static string PerceptionAttributeDescription {
            get {
                return ResourceManager.GetString("PerceptionAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perception.
        /// </summary>
        internal static string PerceptionAttributeTitle {
            get {
                return ResourceManager.GetString("PerceptionAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Physical, brute strength of the character.
        ///Affects melee weapon damage.
        ///Acts as a restriction on the wearing of heavy equipment..
        /// </summary>
        internal static string PhysicalStrengthAttributeDescription {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Physical Strength.
        /// </summary>
        internal static string PhysicalStrengthAttributeTitle {
            get {
                return ResourceManager.GetString("PhysicalStrengthAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Put into {0}.
        /// </summary>
        internal static string PutPropInContainerButtonTitleTemplate {
            get {
                return ResourceManager.GetString("PutPropInContainerButtonTitleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aux.
        /// </summary>
        internal static string SlotAux {
            get {
                return ResourceManager.GetString("SlotAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body.
        /// </summary>
        internal static string SlotBody {
            get {
                return ResourceManager.GetString("SlotBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hand.
        /// </summary>
        internal static string SlotHand {
            get {
                return ResourceManager.GetString("SlotHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Head.
        /// </summary>
        internal static string SlotHead {
            get {
                return ResourceManager.GetString("SlotHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string StartGameButtonTitle {
            get {
                return ResourceManager.GetString("StartGameButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Super.
        /// </summary>
        internal static string SuperAttributeValueTitle {
            get {
                return ResourceManager.GetString("SuperAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Off.
        /// </summary>
        internal static string SwitchAutomodeButtonOffTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        internal static string SwitchAutomodeButtonOnTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autoplay: {0}.
        /// </summary>
        internal static string SwitchAutomodeButtonTitle {
            get {
                return ResourceManager.GetString("SwitchAutomodeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take in inventory.
        /// </summary>
        internal static string TakePropInInventoryButtonTitle {
            get {
                return ResourceManager.GetString("TakePropInInventoryButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dehydration!.
        /// </summary>
        internal static string ThristCriticalConditionTitle {
            get {
                return ResourceManager.GetString("ThristCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy thrist.
        /// </summary>
        internal static string ThristLesserConditionTitle {
            get {
                return ResourceManager.GetString("ThristLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thrist.
        /// </summary>
        internal static string ThristStrongConditionTitle {
            get {
                return ResourceManager.GetString("ThristStrongConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ubnormal.
        /// </summary>
        internal static string UbnormalAttributeValueTitle {
            get {
                return ResourceManager.GetString("UbnormalAttributeValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use.
        /// </summary>
        internal static string UseCommandButtonTitle {
            get {
                return ResourceManager.GetString("UseCommandButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mortal wound!.
        /// </summary>
        internal static string WoundCriticalConditionTitle {
            get {
                return ResourceManager.GetString("WoundCriticalConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lesser wound.
        /// </summary>
        internal static string WoundLesserConditionTitle {
            get {
                return ResourceManager.GetString("WoundLesserConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strong wound.
        /// </summary>
        internal static string WoundStrongConditionTitle {
            get {
                return ResourceManager.GetString("WoundStrongConditionTitle", resourceCulture);
            }
        }
    }
}
