name: Test and Codecov report

on:
  pull_request:
    branches:
      - master
    tags:
      - 'v*.*.*'
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

env:
  TEST_RESULT_PATH: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/TestResults/

jobs:

  test_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_suite:
          - Zilon.Core.UnitTests
          - Zilon.Core.FunctionalTests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Run ${{ matrix.test_suite }} in Release and collect coverage
      env:
        ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OUTPUT: 1
      run: |
        cd ./Zilon.Core
        dotnet test ${{ matrix.test_suite }}.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutput=${{env.TEST_RESULT_PATH}} /p:CoverletOutputFormat=\"cobertura,json\" /p:MergeWith="${{env.TEST_RESULT_PATH}}coverage.json" /p:SkipAutoProps=true /p:ExcludeByAttribute=\"Obsolete,GeneratedCode,CompilerGenerated\" /p:ExcludeByFile="**/Zilon.Core.Tests.Common/*.cs" /maxcpucount:1
    - name: Publish coverage report to codecov.io
      uses: codecov/codecov-action@v1
      with:
        flags: ${{ matrix.test_suite }}
        directory: ${{env.TEST_RESULT_PATH}}
        working-directory: ${{env.TEST_RESULT_PATH}}
        files: ./coverage.cobertura.xml
        fail_ci_if_error: true

  test_debug:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_suite:
          - Zilon.Core.UnitTests
          - Zilon.Core.FunctionalTests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Run ${{ matrix.test_suite }} in Debug
      env:
        ZILON_LIV_SCHEME_CATALOG: /home/runner/work/Zilon_Roguelike/Zilon_Roguelike/Zilon.Client/Assets/Resources/Schemes
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OUTPUT: 1
      run: |
        cd ./Zilon.Core
        dotnet test ${{ matrix.test_suite }}.sln --configuration Debug